image: rust:latest

stages:
  - build
  - test

variables:
  CARGO_TERM_COLOR: always
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

fmt:
  stage: build
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  allow_failure: true

clippy:
  stage: build
  script:
    - rustup component add clippy
    - cargo clippy --workspace --all-targets --all-features -- -D warnings
  allow_failure: true

build:
  stage: build
  script:
    - cargo build --workspace

test:
  stage: test
  script:
    - cargo test --workspace

sonarcloud-check:
  stage: test
  image: sonarsource/sonar-scanner-cli:latest
  script:
    - echo "Running SonarCloud analysis..."
    - |
      sonar-scanner
        -Dsonar.organization.key=welsy
        -Dsonar.projectKey=meemy-group_projini
        -Dsonar.sources=.
        -Dsonar.host.url=https://sonarcloud.io
        -Dsonar.login=$SONAR_TOKEN
  only:
    - merge_requests
    - main
    - develop
  allow_failure: false
