image: rust:latest

stages:
  - build
  - test

variables:
  CARGO_TERM_COLOR: always
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

fmt:
  stage: build
  script:
    - rustup component add rustfmt
    - cargo fmt --all -- --check
  allow_failure: true

clippy:
  stage: build
  script:
    - rustup component add clippy
    - cargo clippy --workspace --all-targets --all-features -- -D warnings
  allow_failure: true

build:
  stage: build
  script:
    - cargo build --workspace

test:
  stage: test
  script:
    - cargo test --workspace

sonarcloud-check:
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - master
    - develop
